# Gola - iv have to ensure the package and dependency have been audiited for security 
name: Dependency Scan 

on:
   workflow_call


jobs: 
      dependency-scan:
             runs-on: ubuntu-latest
             steps:
               - name: Code Chekcout 
                 uses: actions/checkout@v7
                
               - name: Setup Go
                 uses: actions/setup-go@v6
                 with:
                   go-version: 1.23
                   go-version-file: 'go.mod'
                   cache-dependency-path: go.sum

               - name: Install Govulnchekc
                 run: go install golang.org/x/vuln/cmd/govulncheck@v1.1.3 

               - name: goVulncheck
                 continue-on-error: true 
                 run: govulncheck ./... > govulncheck-report.txt
                 working-directory: backend

               - name: Uploaded Report to artifacts
                 if: always() #Ensure Reoort upload even if tests fail
                 uses: actions/upload-artifact@v4
                 with:
                   name: dependency-scan-report
                   path: reports/dependency-report.txt
                   retention-days: 5

               - name: Setup Node
                 uses: actions/setup-node@v6
                 with:
                   node-version: '22'
                   cache: npm
                   cache-dependency-path: frontend/package-lock.json    

               - name: Run dependency scan for Node
                 run: npm audit
                 working-directory: frontend
               
                 


