# Gole -  To run end to end devsecops pipline 

name: DevSecOps


on:
  push: 
      branches: [master]

jobs:
    ## ------------------------ CI---------------------------------------

    # Code stage (with shifr left )
    code-quality: 
        uses: ./.github/workflows/code-quality.yml

    # Secret Scanning
    secreate-scaning:
        uses: ./.github/workflows/secreate-scaning.yml 

   # Dependency check 
    dependency-checks:
        uses: ./.github/workflows/dependency-scan.yml

   # Docker  check 
    docker-checks:
        uses: ./.github/workflows/docker-scan.yml
        secrets: inherit

   # Sonar Qube
    sonar-qube:
        uses: ./.github/workflows/sonar-scan.yml
        secrets: inherit
        
   # Code-Tests

    code-tests:
        uses: ./.github/workflows/code-tests.yml


    # Push-to-dockerhub

    docker-push:
         uses: ./.github/workflows/docker-push.yml
         needs: [code-quality,code-tests,sonar-qube,docker-checks,dependency-checks,secreate-scaning]
         secrets: inherit

    ###--- CD-------

    deploy:
        needs: [docker-push]
        uses: ./.github/workflows/deploy.yml
        secrets: inherit

   