# Goal to inatsll multipul version  of go and linting for multiple version 
name: Go linter 

on:
 
    workflow_dispatch:

jobs:
    code-format:
        runs-on: ubuntu-latest
        strategy:
           fail-fast: false
           matrix:
               go: ['1.22','1.23','1.24']
        steps:
           - name: Setup Go
             uses: actions/setup-go@v6
             with:
              go-version: ${{ matrix.go }}
              go-version-file: 'go.mod'
              check-latest: false
              cache-dependency-path: go.sum

           - name: Run go Formatter
             run: go fmt
             working-directory: backend

           - name: Run go vet
             run: go vet
             working-directory: backend

           - name: Run Tests
             run: go test
             working-directory: backend 
              